### ISSUE TITLE
Balance usd, tokens and store prices

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/FloodIssues#199]
IMO currently everything is way too expensive in the store if you see it from a USD point of view. Heavens wrath costs $49. This scares away purchases and that's pretty understandable.

It's also too easy to get tokens using ingame cash I believe.

I propose to change the USD -> Tokens equation to: ```cost = tokens^0.47 - 0.8```, which would give this table:
![excel_2016-12-24_22-50-20](https://cloud.githubusercontent.com/assets/2332094/21468994/c544078c-ca32-11e6-99a8-a1558805f7a0.png)
Note how this also encourages to buy tokens in bigger bulks, increasing our profit.
Heavens wrath now costs ~$14.

I don't want to do this out of greed, but currently it's dumb because nobody utilizes our content because it's too damn expensive. There's only 10 people who own the heaven's wrath...

I also think we should generally lower prices of shit in the store, aswell as increase the ingamecash->token cost.

Current ingamecash->tokens equation is: ```cost = tokens * 2000```

Discuss ideas please and concrete new levels.

**Comment by Jiwer** [comment]
> increasing our **profit**

This statement doesn't sit well with me.

I personally don't find heavens wrath very appealing, so I see why so little people have it. I mean I could just get like 5 badass player models instead of some hat. 333 tokens for it is absurd imo.

> I also think we should generally lower prices of shit in the store, aswell as increase the ingamecash-token cost.

Why? Let's say to buy a fish I need $10 and I get $1 from every pound of wheat I sell. Now the fish costs $5 but I only make $1 from every two pounds of wheat I sell. In both scenarios I would still need to farm 10 pounds of wheat. Nothing would change.

**Comment by Donkie** [comment]
> This statement doesn't sit well with me.
I am by no means greedy, but we have spent a lot of time and resources on a system that isn't being used because nobody ever buys tokens with USD. We have also come to realization that, while we get a bunch of VIP purchases, many of them are being disputed.

> Nothing would change.
What would change is that USD->token purchases would be more valuable, aswell would other token rewards become more valuable, such as from gifts or achievements.

But yeah this is all debateable, which is why I made this issue. I just believe the current situation is shit and we need some real strategy and planning behind our economies.

**Comment by Jiwer** [comment]
What I notice from looking at ssg's recent donations is that people actually do buy points with USD on their server. This is probably because any decent model in their shop is thousands of points (some upwards of 40k), and you only receive 10 points every 10 minutes, making getting the models legit nearly impossible without buying them with IRL money. Pretty scummy imo and I wouldn't really be happy if you followed in their foot steps.

It's hard to get any models in your store as I could just grind for a day and get whatever I want. Even if you were to make these changes I really don't see why anyone would buy them with real money. The playtime required to get the models wouldn't change.  Plus I don't find any models in the store particularly appealing, but that's just me.

**Comment by Jiwer** [comment]
Unable to edit my post on mobile. It's not hard to get any models in your store.* I'll edit and delete this comment after I'm able to use my PC again.

**Comment by bayrock** [comment]
@Jiwer Donkie isn't proposing that we restrict any content. He actually wants to make it more available.

I support and agree with the theory. Not sure about details.

**Comment by Jiwer** [comment]
Alright, well like I said above is that I do agree that ~$50 for ~300 tokens was a bit ridiculous. So I do agree with the new equation.

**Comment by SergeantOrange** [comment]
I proposed this on discord, donkie liked it so yea...
cost = tokens ^ 0.75 / 3
