### ISSUE TITLE
Special props issues

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/FloodIssues#568]
Comment on bugs/requests/tweaks on special props here.

- [x] Countermeasure needs to deactivate properly on removal, will currently make props immune to unweld and fire forever if destroyed while activated

**Comment by RicksBeehive** [comment]
- [ ] Stop them from being used in build/flooding phase, it's annoying for people to walk around with weapons pregame even if they can't do anything with them, they can also waste a use of their prop.
- [ ] Shouldn't be able to use gun cabinet on pirate event.
- [ ] Shouldn't be able to use other teams special props.
- [ ] Gun cabinet gives weapons like "Test swep".

Otherwise looks good, seems fairly balanced and would probably like to see how effective they are in actual matches befor proper balancing
